"""Añadir campo weather a eventos

Revision ID: d3b48e97b18f
Revises: 62d8f284e757
Create Date: 2025-05-18 18:24:33.545249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3b48e97b18f'
down_revision = '62d8f284e757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weather', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('weather')

    # ### end Alembic commands ###
